import { Case, Hearing, Employee } from './types';

export const MOCK_CASES: Case[] = [
  {
    id: '1',
    caseNumber: 'ERB-2026-001',
    title: 'Grievance: Overtime Dispute',
    type: 'Grievance',
    status: 'Open',
    filingDate: '2026-03-10',
    hearingDate: '2026-04-05',
    employee: 'John Doe',
    union: 'Local 123',
    department: 'Operations',
    assignedTo: 'Sarah Miller',
    description: 'Employee claims overtime pay was incorrectly calculated for the weekend of March 7-8.',
  },
  {
    id: '2',
    caseNumber: 'ERB-2026-002',
    title: 'Disciplinary: Safety Violation',
    type: 'Disciplinary',
    status: 'Pending',
    filingDate: '2026-03-15',
    employee: 'Jane Smith',
    department: 'Logistics',
    assignedTo: 'Robert Chen',
    description: 'Reported failure to wear required PPE in the warehouse on March 14.',
  },
  {
    id: '3',
    caseNumber: 'ERB-2026-003',
    title: 'Arbitration: Contract Interpretation',
    type: 'Arbitration',
    status: 'Open',
    filingDate: '2026-03-18',
    hearingDate: '2026-04-12',
    employee: 'Multiple',
    union: 'Local 123',
    department: 'Manufacturing',
    assignedTo: 'Sarah Miller',
    description: 'Dispute over the interpretation of Article 14 regarding shift differentials.',
  },
  {
    id: '4',
    caseNumber: 'ERB-2026-004',
    title: 'ULP: Information Request',
    type: 'Unfair Labor Practice',
    status: 'Closed',
    filingDate: '2026-02-20',
    employee: 'Union Rep',
    union: 'Local 456',
    department: 'Human Resources',
    assignedTo: 'Michael Brown',
    description: 'Union alleges management failed to provide requested documents for collective bargaining.',
  },
];

export const MOCK_HEARINGS: Hearing[] = [
  {
    id: 'h1',
    caseId: '1',
    caseNumber: 'ERB-2026-001',
    date: '2026-04-05',
    time: '10:00 AM',
    location: 'Conference Room B',
    type: 'Initial Hearing',
    status: 'Scheduled',
  },
  {
    id: 'h2',
    caseId: '3',
    caseNumber: 'ERB-2026-003',
    date: '2026-04-12',
    time: '02:00 PM',
    location: 'Main Hall',
    type: 'Arbitration Session',
    status: 'Scheduled',
  },
];

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'e1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    department: 'Operations',
    position: 'Technician',
    unionMember: true,
  },
  {
    id: 'e2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    department: 'Logistics',
    position: 'Warehouse Lead',
    unionMember: false,
  },
];
